### ISSUE TITLE
Finalize & Ship Auk docs

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#421]
This is a ZenHub Epic.  You'll need the ZenHub plugin to see everything.

**Remaining Tasks (in order)**

- [x] Auth API docs
- [x] Hook Docs
- [x] Chat guide updates
- [x] Merge `auk-reorg` to `auk` branch
- [x] Finalize Feathers basics guide
- [x] Finish feathers-client API docs
- [x] Move over/update any old/proposed guides into the guides section or as blog posts on medium
- [x] Tag feathers-docs `master` branch and cut a `pre-auk` branch (name still TBD)
- [x] Merge feathers-docs `auk` to `master` and tag it

**Comment by ekryski** [comment]
@feathersjs/core-team I think we can probably close this one out now. All the remaining open tasks can be completely stand-alone.

**Comment by ekryski** [comment]
nvm still waiting on #476, #491, and #505.

**Comment by ekryski** [comment]
We shipped the new docs earlier this week and have moved the old ones over to https://legacy.docs.feathersjs.com/.

A few sections of the guides just need a bit of updating but overall all the API docs are in place and up to date. Just a couple small sections to update and then I think we'll be good to close this out. 🎉

**Comment by ekryski** [comment]
This is now officially closed! 💥

You can read about the release announcement here: https://blog.feathersjs.com/the-auk-takes-flight-c4b3c070c6d.

We'll be migrating the old guides over to blog posts on Medium over the next while but in the mean time you can still access them at:

https://legacy.docs.feathersjs.com/guides/readme.html
https://legacy.docs.feathersjs.com/frameworks/readme.html
